baseURL = "markchur.ch"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Mark Church"                    
theme = "church"
summaryLength = 100
paginate = 4                         
enableEmoji = true
googleAnalytics = ""                 
disqusShortname = ""                 

[author]                           
  name = "Church"

[blackfriday]
  smartypants = false


[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/"
[[menu.main]]
  name = "Topics"
  weight = 2
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Links"
  weight = 4
  identifier = "links"
  url = "/links/"

[params]
<<<<<<< HEAD
  subTitle = ""                                       
  footerSlogan = ""                                         
  keywords = ["Hugo", "theme","zozo"]                                 
  description = "Mark Church"
=======
  subTitle = ""                                     
  footerSlogan = ""                                       
  keywords = ["Hugo", "theme","zozo"]                        
  description = "Hugo theme zozo example site."             
>>>>>>> ceca000daf8779556c94bf6c79ed74ba00be72bd

  enableSummary = true                       

<<<<<<< HEAD
=======
  enableSummary = true                                                
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
>>>>>>> ceca000daf8779556c94bf6c79ed74ba00be72bd
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = false

