baseURL = "markchur.ch"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Mark Church"                    # site title  # 网站标题
theme = "church"
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "Church"

[blackfriday]
  smartypants = false


[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/"
[[menu.main]]
  name = "Topics"
  weight = 2
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Links"
  weight = 4
  identifier = "links"
  url = "/links/"

[params]
  subTitle = ""                                     
  footerSlogan = ""                                       
  keywords = ["Hugo", "theme","zozo"]                        
  description = "Hugo theme zozo example site."             


  enableSummary = true                                                
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = false

