baseURL = "markchur.ch"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Mark Church"                    
theme = "church"
summaryLength = 100
paginate = 4                         
enableEmoji = true
googleAnalytics = ""                 
disqusShortname = ""                 

[author]                           
  name = "Church"

[blackfriday]
  smartypants = false


[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/"
[[menu.main]]
  name = "Topics"
  weight = 2
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Links"
  weight = 4
  identifier = "links"
  url = "/links/"

[params]
  subTitle = ""                                       
  footerSlogan = ""                                         
  keywords = ["Hugo", "theme","zozo"]                                 
  description = "Mark Church"

  enableSummary = true                       

[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = false

